### ISSUE TITLE
Error de codificado en respuesta

### ISSUE THREAD

**Issue by LibreTitan** [JossMP/reniec#1]
Gracias por compartir tu codigo.

Hay un error en el retorno, los caracteres especiales no los codifica bien.

ejemplo:
Array ( [success] => 1 [result] => Array ( [Paterno] => GAMBOA [Materno] => CAPU�AY [Nombre] => YOSELYN MARILYN [DNI] =>

**Comment by edergar** [comment]
hola buenas noches, estoy intentando correr el código, pero de frente me bota el mensaje de error, agradecería mucho una ayuda por parte de usted. Gracias

**Comment by JossMP** [comment]
error de codificacion de caracteres especiales corregido
